# docker compose for local launch, render.com launches production service using only Dockerfile and its own configuration
name: finfast-native

services:

  db:
    image: postgres:18
    environment:
      POSTGRES_DB: finfast
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"

  kafka:
    image: apache/kafka:4.3.1
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: CONTROLLER://:9093,INTERNAL://:9092,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-init:
    image: apache/kafka:4.3.1
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "Waiting for Kafka..."
        until /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list >/dev/null 2>&1; do
          sleep 2
        done

        echo "Creating topic user-events..."
        /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka:9092 \
          --create \
          --if-not-exists \
          --topic user-events \
          --partitions 1 \
          --replication-factor 1

        echo "Kafka topic user-events is ready."

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile.native
      args:
        QUARKUS_PROFILE: dev
    env_file:
      - .env.dev
    ports:
      - "8082:8082"
    depends_on:
      - db

  expense-service:
    build:
      context: ./services/expense-service
      dockerfile: Dockerfile.native
    env_file:
      - .env.dev
    ports:
      - "8081:8081"
    depends_on:
      - db

volumes:
  postgres-data:
    external: true
    name: finfast_postgres-data