spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    table: expense_flyway_schema_history
  kafka:
    consumer:
      group-id: expense-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    properties:
      sasl.mechanism: PLAIN
      isolation.level: read_committed

finfast:
  jwt:
    issuer: finfast-api
  expense:
    purge:
      cron: "0 0 3 * * *"

springdoc:
  api-docs.enabled: false
  swagger-ui.enabled: false
