server:
  port: 8081

spring:
  datasource:
    # DATABASE_HOST will be postgres for local launch in docker container
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/finfast
    username: postgres
    password: postgres

logging:
  level:
    root: INFO
    org.example.finfast: DEBUG
    org.springframework.security: DEBUG

finfast:
  jwt:
    private-key-b64: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDJfbPwPKFzDjj2pDsbYHjf7Pw5FsSNc5M8lgBtIqRMBFhkFjPauaKmU2m/zdqf2/tjgvEkFwl3SySZRIFHkhCW18Od/yXbNCXyp4IC2V9qgf/Sy4RVM1m6JaRwjbCWOHHC79CftaltVNhBt55xJTZZXu4nkjC2vOVm51Wo6zcT+0eQPLk4Y1QaCE32gh/jorbzmdZ8O3Ts2XuxJA2PSpsrMmdA9EjHP5VpolivwXSeuZShQghRn30tJs3yOhjopZE8mBDiliirAtGe/reYsdR2m2vsbbkRuQtqGfnrOef9dpHLQt/xvRpMSgMsEKfoYBP6wjRBWGXiDjcJ6Uq2nsKzAgMBAAECggEAUrGddN5dYIwYwtj6TS0VzslDZua6OleRuQ7TE/dguLYb1M/r7ju7zklzoD2LGYq+LMQj1a0CvIwBdEnSSR5gYpgg96oszj8jx+gJisPNzjeWV9wg7prJm4UxbOQp8i0uO1QTKkjzRSTKMIZ8p3EfUiSM136/MXBrMgWFeXM3wqHlu4q4+tKA5BHbtK1+ZqdjS6mqL6C0/A0Ylm8wiHF88FdjQECOW+Ls+qczn2AHebAXI8143mb7Pmy6QFrJ4TPjS22Os6WSSOL3I8iJYiYqL/AebaKHltScssVrWdv371m7rIg6IzDPad5kCWYy2cgVT+tIxs94TevQGSOUncQ2+QKBgQDKS+VeIo7RN9qP62oCLTdGcEuzJLiQ9KQM9WbRpqkJ1eY9caQLVf1rDM23pQObk+cDhQn/Ul5O0ybowsFWtQHWUI6NRTbexkDyZssL3ySbtUWsOvDFS+/kvkNAbhX+YywqJAmj+ieR8t2iSxHHms2yBims9qLGe/0dpezDWKPKVQKBgQD++xGm7WdJr4cDCF7Gf+nOxGD0xyzOR+QRgtWecLw+EEzJLdsA6iG2Ckpj2ypcj9GZAGIPL1IlJ0xwvndz0qLveeuWxaiOp77zIhXoNp6lRD1eyRe1mVXzxDZ0DcxSfsciox9SCO9/n+Kqmw6AhCNPI4W5Zu/XhXlxSa6s8xZw5wKBgC48iJEqbuAM1wyb7t/Oe9rCodqxIuomsDQyBq0WXX5dAEG87pSUs9Y61+4Ibjmp5VwdlTphFiMICdWbZdsuhdv5D4vkbPUf9QoySmhNOS3JkcIaupstjwgGIJLiVm6NNjPvhrCO5WprSxLj+41WqXruA6p/uJaLEkArg2DmqpD9AoGARMxTl/nIe75LrIrOn7qVyH9+Na2kLkiBhiQKJYT/lbNqNIIV7GpADFE8fzL8fBsmD6Vlz/kRrgqremQ58NttsTXxVi4g69ThFdMlnBFYvvjpojCaIBqucWaI1sl+Tuf8LSFcaxMUJBhs3WGXCSAeMtU/2KWooztVaDbcVbgFXxMCgYBiBc14+BuhbMUh9lbRTt15UHFPHAah2wjIpMQLPC2Y4x1PXVMaCSjgrSXIjJ0t2siGanamIUQz1ZGZ6mnnhs+pN0wprfrW6o1Q1Zj8Xfsp8pFCt6mYC0DP3b1iZFcEEQEPwMr7MiiEo/+vAhx4V1T6CREiNrkM4jTWBVKsf2NU2A==
    public-key-b64: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyX2z8Dyhcw449qQ7G2B43+z8ORbEjXOTPJYAbSKkTARYZBYz2rmiplNpv83an9v7Y4LxJBcJd0skmUSBR5IQltfDnf8l2zQl8qeCAtlfaoH/0suEVTNZuiWkcI2wljhxwu/Qn7WpbVTYQbeecSU2WV7uJ5IwtrzlZudVqOs3E/tHkDy5OGNUGghN9oIf46K285nWfDt07Nl7sSQNj0qbKzJnQPRIxz+VaaJYr8F0nrmUoUIIUZ99LSbN8joY6KWRPJgQ4pYoqwLRnv63mLHUdptr7G25EbkLahn56znn/XaRy0Lf8b0aTEoDLBCn6GAT+sI0QVhl4g43CelKtp7CswIDAQAB
  clientUrl: http://localhost:5173
