server:
  port: 8081

spring:
  datasource:
    # DATABASE_HOST will be postgres for local launch in docker container
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/finfast
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-client-secret";

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level ${PID:- } --- [%thread] %logger : %msg%n%wEx"
  level:
    root: INFO
    org.example.finfast: DEBUG
    org.springframework.security: DEBUG
    com.nimbusds.jose: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG

finfast:
  auth-service:
    url: http://localhost:8082
  clientUrl: http://localhost:5173
