server:
  port: 8081

spring:
  datasource:
    # DATABASE_HOST will be postgres for local launch in docker container
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/finfast
    username: postgres
    password: postgres

logging:
  level:
    root: INFO
    org.example.finfast: DEBUG
    org.springframework.security: DEBUG

finfast:
  jwt:
    public-key-b64: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyX2z8Dyhcw449qQ7G2B43+z8ORbEjXOTPJYAbSKkTARYZBYz2rmiplNpv83an9v7Y4LxJBcJd0skmUSBR5IQltfDnf8l2zQl8qeCAtlfaoH/0suEVTNZuiWkcI2wljhxwu/Qn7WpbVTYQbeecSU2WV7uJ5IwtrzlZudVqOs3E/tHkDy5OGNUGghN9oIf46K285nWfDt07Nl7sSQNj0qbKzJnQPRIxz+VaaJYr8F0nrmUoUIIUZ99LSbN8joY6KWRPJgQ4pYoqwLRnv63mLHUdptr7G25EbkLahn56znn/XaRy0Lf8b0aTEoDLBCn6GAT+sI0QVhl4g43CelKtp7CswIDAQAB
  clientUrl: http://localhost:5173
