quarkus:
  http:
    port: ${PORT}
    cors:
      origins: ${CLIENT_URL}

  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    jdbc:
      url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}

  tls:
    aiven-kafka:
      trust-store:
        pem:
          certs: /etc/secrets/aiven-ca.pem

kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS}
  security:
    protocol: SASL_SSL
  sasl:
    jaas:
      config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
  tls-configuration-name: aiven-kafka

logging:
  level:
    root: INFO
    org.example.finfast: WARN
    org.springframework.security: WARN

finfast:
  jwt:
    private-key-b64: ${FINFAST_JWT_PRIVATE_KEY_B64}
    public-key-b64: ${FINFAST_JWT_PUBLIC_KEY_B64}
  google:
    client-id: ${GOOGLE_CLIENT_ID}