quarkus:
  application:
    name: auth-service
  package:
    output-name: auth-service

  http:
    port: 8082
    cors:
      enabled: true
      methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      headers: Content-Type,Authorization

  datasource:
    db-kind: postgresql

  hibernate-orm:
    schema-management:
      strategy: validate

  flyway:
    migrate-at-start: true
    table: auth_flyway_schema_history

finfast:
  jwt:
    issuer: finfast-api
    key-id: finfast-rs256-1
