quarkus:
  http:
    port: 8082
    cors:
      origins: http://localhost:5173

  datasource:
    username: postgres
    password: postgres
    jdbc:
      # DATABASE_HOST will be postgres for local launch in docker container
      url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/finfast

kafka:
  bootstrap:
    servers: localhost:9094
  security:
    protocol: SASL_PLAINTEXT
  sasl:
    jaas:
      config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-client-secret";

logging:
  level:
    root: INFO
    org.example.finfast: DEBUG
    org.springframework.security: DEBUG

finfast:
  google:
    client-id: 1034212438621-0aqca3sr7q7ps8e3p2fs2e586lhjcp53.apps.googleusercontent.com
