server:
  port: 8081

spring:
  # Временные настройки встроенной БД для первого запуска без Docker
  datasource:
    url: jdbc:h2:file:./data/finfast
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
