server:
  port: ${PORT}

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

logging:
  level:
    root: INFO
    org.example.finfast: WARN
    org.springframework.security: WARN

finfast:
  jwt:
    private-key-b64: ${FINFAST_JWT_PRIVATE_KEY_B64}
    public-key-b64: ${FINFAST_JWT_PUBLIC_KEY_B64}
  clientUrl: ${CLIENT_URL}