FROM ghcr.io/graalvm/graalvm-community:25 AS build

WORKDIR /app

ARG QUARKUS_PROFILE=prod

COPY gradlew .
COPY gradle gradle
COPY gradle.properties .
COPY settings.gradle.kts .
COPY build.gradle.kts .

RUN chmod +x ./gradlew

RUN --mount=type=cache,id=finfast-auth-gradle,target=/root/.gradle \
    ./gradlew dependencies \
    --no-daemon

COPY src src

RUN --mount=type=cache,id=finfast-auth-gradle,target=/root/.gradle \
    ./gradlew quarkusBuild \
    -Dquarkus.profile=${QUARKUS_PROFILE} \
    -Dquarkus.native.enabled=true \
    -Dquarkus.package.jar.enabled=false \
    --no-daemon


FROM debian:bookworm-slim

WORKDIR /app

COPY --from=build /app/build/auth-service-runner ./auth-service

RUN chmod +x auth-service

EXPOSE 8082

ENTRYPOINT ["./auth-service"]